cal/urls.py
from django.conf.urls import url

from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^$',views.home_page , name='home_page'),
    url(r'^calculator/$',views.calculator, name='calculator')

]

simple_calculator/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cal.urls')),
]

cal/models.py
from django.db import models

# Create your models here.

cal/views.py
from django.shortcuts import render

# Create your views here.
def home_page(request):
    return render(request,'home.html')

def calculator(request):
    a = float(request.GET['number a'])
    b = float(request.GET['number b'])
    act = request.GET['action']
    context = {'a':a,'b':b,'act':act}
    if act =='+':
        context['result'] = a+b
    elif act == '-':
        context['result'] = a-b
    elif act == '*':
        context['result'] = a*b
    else:
        context['result'] = a/b
    return render(request,'calculator.html',context)

cal/templates/calculator.html
<body style='background-color:lightgrey; font-size:150%;' >
    <h1>Calculator Online</h1>
    Result: {{a}} {{act}} {{b}} = {{result}}

<Form action='../'><input type='submit' value='Back'></form><br>

cal/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Calculator</title>
</head>
<body>
<h1>Calculator Online</h1>
<Form action="{% url 'cal:calculator' %}" method="get">
Number a:<br>
<input type='text' name='number a' size='40' autofocus><br>
Number b:<br><input type='text' name='number b' size='40'>
<h2>What you do? :</h2>
<input type='radio' name='action' value='+' checked>Plus<br>
<input type='radio' name='action' value='-'>Minus<br>
<input type='radio' name='action' value='*'>Multiplied<br>
<input type='radio' name='action' value='/'>Divided<br><br>
<input type='submit' value='Submit'></form><br>

</body>
</html>